name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - elixir: "1.17"
            otp: "25"
          - elixir: "1.17"
            otp: "26"
          - elixir: "1.17"
            otp: "27"
          - elixir: "1.16"
            otp: "24"
          - elixir: "1.16"
            otp: "25"
          - elixir: "1.16"
            otp: "26"
          - elixir: "1.15"
            otp: "24"
          - elixir: "1.15"
            otp: "25"
          - elixir: "1.15"
            otp: "26"
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - run: mix deps.get
      - run: mix format --check-formatted
      - run: mix test
